Repository sustainable-computing-io/kepler, pull requests merged in 2022-09, with the labels that each got.

#156 remove the dram energy from rapl pkg energy calculation
  pkg/collector/node_energy.go
  pkg/collector/reader.go
  pkg/config/config.go
  pkg/model/estimate.go
  pkg/power/rapl/source/estimate.go
  pkg/power/rapl/source/sysfs.go
Labels: bug

#167 Update go test to run all go vet checks
  Makefile
Labels: enhancement

#168 Add support for golint
  .golangci.yml
  Makefile
  hack/golint.sh
Labels: enhancement

#170 Add golint test to CI
  .github/workflows/golangci-lint.yml
Labels: enhancement

#165 update integration test to use cluster up and sync
  .github/workflows/integration_test.yml
  .github/workflows/unit_test.yml
  cluster-up/cluster/kind/README.md
  cluster-up/cluster/kind/common.sh
Labels: enhancement

#174 Update kepler namespace from monitoring to kepler
  grafana-dashboards/Kepler-Exporter.json
  grafana-dashboards/legacy/Kepler-Exporter-Dashboard-openshift.json
  grafana-dashboards/legacy/Kepler-Exporter-Dashboard.json
  hack/cluster-deploy.sh
  manifests/kubernetes/deployment.yaml
  manifests/openshift/kepler/00-kepler-scc.yaml
  manifests/openshift/kepler/01-kepler-install.yaml
Labels: enhancement

#175 refactor git workflows
  .github/workflows/gofmt.yml
  .github/workflows/unit_test.yml
Labels: enhancement

#176 fix all lint errors
  .golangci.yml
  bpfassets/perf_event/perf_event.c
  cmd/exporter.go
  pkg/attacher/bcc_attacher.go
  pkg/attacher/bcc_attacher_stub.go
  pkg/bpfassets/assets.go
  pkg/bpfassets/perf_event_bindata.go
  pkg/cgroup/path_handler.go
  pkg/cgroup/slice_handler.go
  pkg/cgroup/slice_handler_test.go
  pkg/cgroup/stat_reader.go
  pkg/collector/collector.go
  pkg/collector/collector_test.go
  pkg/collector/metrics.go
  pkg/collector/metrics_test.go
  pkg/collector/node_energy.go
  pkg/collector/pod_energy.go
  pkg/collector/reader.go
  pkg/collector/types.go
  pkg/config/config.go
  pkg/model/estimate.go
  pkg/model/estimate_test.go
  pkg/model/model.go
  pkg/podlister/byte_order.go
  pkg/podlister/byte_order_test.go
  pkg/podlister/cgroup_stats.go
  pkg/podlister/kubelet_pod_lister.go
  pkg/podlister/pod_lister_test.go
  pkg/podlister/resolve_container.go
  pkg/podlister/suite_test.go
  pkg/power/acpi/acpi.go
  pkg/power/gpu/gpu_nvml.go
  pkg/power/rapl/source/estimate.go
  pkg/power/rapl/source/msr_util.go
  pkg/power/rapl/source/sysfs.go
  pkg/power/rapl/source/sysfs_util.go
  scripts/bindata.sh
Labels: enhancement

#145 Model Server Energy Prediction
  pkg/model/model.go
Labels: enhancement

#235 Add support to deploy prometheus operator via make cluster-up
  .github/workflows/integration_test.yml
  cluster-up/cluster/kind/common.sh
Labels: bug, enhancement

#244 Remove the dram energy from the host other components energy consumption
  pkg/collector/node_energy.go
Labels: bug

#270 Refactor the PackageEnergy to RAPLEnergy
  pkg/collector/collector.go
  pkg/collector/collector_test.go
  pkg/collector/node_energy.go
  pkg/collector/reader.go
  pkg/power/rapl/power.go
  pkg/power/rapl/source/dummy.go
  pkg/power/rapl/source/estimate.go
  pkg/power/rapl/source/msr.go
  pkg/power/rapl/source/msr_util.go
  pkg/power/rapl/source/package_energy.go
  pkg/power/rapl/source/sysfs.go
Labels: enhancement
