Repository sustainable-computing-io/kepler, pull requests merged in 2025-07, with the labels that each got.

#2192 chore(compose): expose vm metrics in config
  compose/dev/kepler-dev/etc/kepler/config.yaml
Labels: chore

#2183 feat(device/cpu): aggregate multi-socket zones into single zone
  internal/device/energy_zone.go
  internal/device/energy_zone_test.go
  internal/device/fake_cpu_power_meter.go
  internal/device/rapl_sysfs_power_meter.go
  internal/device/rapl_sysfs_power_meter_test.go
  internal/exporter/prometheus/collector/power_collector.go
  internal/exporter/prometheus/collector/power_collector_concurrency_test.go
  internal/exporter/prometheus/collector/power_collector_test.go
Labels: feat

#2198 docs: update governance maintainer
  .github/ISSUE_TEMPLATE/maintainer_nominate.yaml
  GOVERNANCE.md
  MAINTAINERS.md
  OWNERS
Labels: docs

#2199 feat(monitor): add configurable limit for terminated workloads tracking
  cmd/kepler/main.go
  compose/dev/kepler-dev/etc/kepler/config.yaml
  config/config.go
  config/config_test.go
  docs/configuration/configuration.md
  hack/config.yaml
  internal/monitor/monitor.go
  internal/monitor/options.go
  manifests/k8s/configmap.yaml
Labels: feat

#2206 feat(config): add configurable web server listen addresses
  cmd/kepler/main.go
  compose/dev/kepler-dev/etc/kepler/config.yaml
  config/config.go
  config/config_test.go
  docs/configuration/configuration.md
  hack/config.yaml
  manifests/k8s/configmap.yaml
Labels: feat

#2202 feat: implement energy-based terminated workload tracking
  config/config.go
  internal/device/cpu_power_meter.go
  internal/device/fake_cpu_power_meter.go
  internal/device/rapl_sysfs_power_meter.go
  internal/device/rapl_sysfs_power_meter_test.go
  internal/exporter/prometheus/collector/power_collector.go
  internal/exporter/prometheus/collector/power_collector_test.go
  internal/monitor/clone_test.go
  internal/monitor/container.go
  internal/monitor/container_power_test.go
  internal/monitor/mock_utils.go
  internal/monitor/monitor.go
  internal/monitor/monitor_collection_test.go
  internal/monitor/monitor_concurrency_test.go
  internal/monitor/monitor_snapshot_integration_test.go
  internal/monitor/monitor_test.go
  internal/monitor/node_test.go
  internal/monitor/options.go
  internal/monitor/options_test.go
  internal/monitor/pod.go
  internal/monitor/pod_power_test.go
  internal/monitor/process.go
  internal/monitor/process_power_test.go
  internal/monitor/terminated_resource_tracker.go
  internal/monitor/terminated_resource_tracker_test.go
  internal/monitor/types.go
  internal/monitor/vm.go
  internal/monitor/vm_test.go
Labels: feat, chore

#2210 ci: remove reboot branch from config-change workflow
  .github/workflows/config-change.yaml
Labels: ci

#2213 ci: comment only if related config files are not updated
  .github/workflows/config-change.yaml
Labels: ci

#2214 [ci]: add depbot, and scorecord back to CI
  .github/dependabot.yml
  .github/workflows/push.yaml
  .github/workflows/scorecard.yml
Labels: ci

#2216 chore: add make help target
  Makefile
Labels: chore

#2220 feat: add Helm chart for Kepler deployment
  .github/k8s/action.yaml
  .github/workflows/release.yaml
  .pre-commit-config.yaml
  README.md
  docs/user/installation.md
  manifests/helm/kepler/.helmignore
  manifests/helm/kepler/Chart.yaml
  manifests/helm/kepler/templates/_helpers.tpl
  manifests/helm/kepler/templates/configmap.yaml
  manifests/helm/kepler/templates/daemonset.yaml
  manifests/helm/kepler/templates/namespace.yaml
  manifests/helm/kepler/templates/rbac.yaml
  manifests/helm/kepler/templates/service.yaml
  manifests/helm/kepler/templates/servicemonitor.yaml
  manifests/helm/kepler/values.yaml
Labels: feat, ci, docs

#2229 chore: add build args to Dockerfile
  Dockerfile
  Makefile
Labels: chore

#2228 docs: update license svg in README
  README.md
Labels: docs

#2212 docs: add disable and unlimited tracking for maxTerminated
  docs/configuration/configuration.md
Labels: docs

#2234 chore: update issue template for nomination for more details
  .github/ISSUE_TEMPLATE/maintainer_nominate.yaml
Labels: chore

#2237 docs: add comprehensive power attribution guide
  docs/developer/assets/power-attribution.png
  docs/developer/index.md
  docs/developer/power-attribution-guide.md
  docs/index.md
Labels: docs

#2239 ci: ensure that must-gather runs for both K8s deployment
  .github/k8s/action.yaml
Labels: ci

#2233 [docs] Add Gen AI policy in readme and contributing file
  CONTRIBUTING.md
  README.md
Labels: docs

#2248 Use precommit hook for helm lint
  .pre-commit-config.yaml
Labels: chore

#2252 chore(compose): remove old Kepler service
  compose/dev/compose.yaml
  compose/dev/grafana/dashboards/dev/dashboard.json
  compose/dev/grafana/dashboards/dev/kepler-old-vs-new.json
  compose/dev/kepler-latest/etc/kepler/config.yaml
  compose/dev/kepler-old/etc/kepler/kepler.config/ENABLE_PROCESS_METRICS
  compose/dev/kepler-old/etc/kepler/kepler.config/EXCLUDE_SWAPPER_PROCESS
  compose/dev/kepler-old/etc/kepler/kepler.config/EXPOSE_ESTIMATED_IDLE_POWER_METRICS
  compose/dev/kepler-old/etc/kepler/kepler.config/EXPOSE_VM_METRICS
  compose/dev/kepler-old/etc/kepler/kepler.config/PROC_DIR
  compose/dev/kepler-old/etc/kepler/kepler.config/SYS_DIR
  compose/dev/override.yaml
  compose/dev/prometheus/scrape-configs/dev.yaml
Labels: chore

#2253 ci: add validation for compose setup
  .github/compose/action.yaml
  .github/workflows/pr-checks.yaml
Labels: ci
