Repository sustainable-computing-io/kepler, pull requests merged in 2025-06, with the labels that each got.

#2117 chore(dashboard): update the variable name for zone
  compose/dev/grafana/dashboards/dev/dashboard.json
Labels: chore

#2120 ci: make the x-crypto workflow temporarily disable
  .github/workflows/check-x-crypto-deps.yaml
Labels: ci

#2119 fix(container): Improve container ID detection using deepest cgroup path match for nested containerIDs in cgroup path
  internal/resource/container.go
  internal/resource/container_test.go
Labels: fix

#2121 chore(go): use golang 1.23
  .github/workflows/pr-checks.yaml
  .pre-commit-config.yaml
  config/config.go
  config/config_test.go
  go.mod
  internal/exporter/stdout/stdout.go
  internal/exporter/stdout/stdout_test.go
  internal/logger/logger_test.go
  internal/monitor/monitor_concurrency_test.go
Labels: fix, chore

#2125 fix(power): correct power attribution by separating used vs idle power
  .github/workflows/k8s-equinix.yaml
  .github/workflows/k8s.yaml
  internal/exporter/prometheus/collector/power_collector.go
  internal/exporter/prometheus/collector/power_collector_concurrency_test.go
  internal/exporter/prometheus/collector/power_collector_test.go
  internal/exporter/stdout/stdout_test.go
  internal/monitor/container.go
  internal/monitor/container_power_test.go
  internal/monitor/mock_utils.go
  internal/monitor/monitor_collection_test.go
  internal/monitor/monitor_concurrency_test.go
  internal/monitor/monitor_test.go
  internal/monitor/node.go
  internal/monitor/node_test.go
  internal/monitor/process.go
  internal/monitor/process_power_test.go
  internal/monitor/types.go
  internal/monitor/vm.go
  internal/monitor/vm_test.go
  internal/resource/informer.go
  internal/resource/mock_procfs_test.go
  internal/resource/procfs_reader.go
  internal/resource/procfs_reader_test.go
  internal/resource/testdata/procfs/stat
Labels: fix, chore

#2137 test: add coverage for gen-metric-doc tool
  hack/gen-metric-docs/main_test.go
Labels: test

#2135 chore: add .PHONY declarations near to targets
  Makefile
Labels: chore

#2136 ci: add missing check for file changes in equinix workflow
  .github/workflows/k8s-equinix.yaml
Labels: ci

#2134 refactor: energy data structs
  internal/exporter/prometheus/collector/power_collector.go
  internal/exporter/prometheus/collector/power_collector_concurrency_test.go
  internal/exporter/prometheus/collector/power_collector_test.go
  internal/exporter/stdout/stdout.go
  internal/exporter/stdout/stdout_test.go
  internal/monitor/container.go
  internal/monitor/container_power_test.go
  internal/monitor/mock_utils.go
  internal/monitor/monitor_test.go
  internal/monitor/node.go
  internal/monitor/node_test.go
  internal/monitor/process.go
  internal/monitor/process_power_test.go
  internal/monitor/types.go
  internal/monitor/vm.go
  internal/monitor/vm_test.go
  internal/resource/informer.go
  internal/resource/procfs_reader.go
  internal/resource/procfs_reader_test.go
Labels: feat

#2127 feat(pod): added pod power
  cmd/kepler/main.go
  config/config.go
  config/config_test.go
  go.mod
  go.sum
  internal/exporter/prometheus/collector/power_collector.go
  internal/k8s/pod/mock_utils.go
  internal/k8s/pod/pod.go
  internal/k8s/pod/pod_test.go
  internal/monitor/container.go
  internal/monitor/mock_utils.go
  internal/monitor/monitor.go
  internal/monitor/monitor_collection_test.go
  internal/monitor/pod.go
  internal/monitor/process.go
  internal/monitor/types.go
  internal/resource/informer.go
  internal/resource/options.go
  internal/resource/types.go
Labels: feat

#2139 ci: move k8s to run on pr check workflow
  .github/k8s/action.yaml
  .github/workflows/k8s.yaml
  .github/workflows/pr-checks.yaml
Labels: ci

#2145 chore(pod): added tests for pod power
  config/config.go
  config/config_test.go
  internal/exporter/prometheus/collector/power_collector.go
  internal/k8s/pod/pod.go
  internal/k8s/pod/pod_test.go
  internal/logger/logger.go
  internal/monitor/container.go
  internal/monitor/monitor.go
  internal/monitor/monitor_collection_test.go
  internal/resource/informer.go
  internal/resource/mock_procfs_test.go
  internal/resource/procfs_reader_test.go
  internal/resource/types.go
Labels: chore

#2142 docs: include pod level metrics
  .github/workflows/pr-checks.yaml
  docs/metrics/metrics.md
  hack/gen-metric-docs/main.go
Labels: docs

#2131 chore: update dashboard to use active node cpu metric
  compose/dev/grafana/dashboards/dev/dashboard.json
Labels: chore

#2148 feat(node): add node_name to power metrics
  cmd/kepler/main.go
  docs/metrics/metrics.md
  hack/gen-metric-docs/main.go
  hack/gen-metric-docs/main_test.go
  internal/exporter/prometheus/collector/power_collector.go
  internal/exporter/prometheus/collector/power_collector_concurrency_test.go
  internal/exporter/prometheus/collector/power_collector_test.go
  internal/exporter/prometheus/prometheus.go
Labels: feat

#2150 fix(exporter): move WithNodeName option to collector
  cmd/kepler/main.go
  internal/exporter/prometheus/collector/power_collector_test.go
  internal/resource/procfs_reader_test.go
Labels: fix

#2151 chore: remove generation date from markdown
  docs/metrics/metrics.md
  hack/gen-metric-docs/main.go
Labels: chore

#2152 ci: trigger equinix workflow only on source code changes
  .github/workflows/k8s-equinix.yaml
Labels: ci

#2153 ci: ensure pod level metrics are exported
  .github/k8s/action.yaml
  .github/workflows/k8s-equinix.yaml
  manifests/k8s/daemonset.yaml
Labels: ci

#2157 fix(tests): refactored power collector tests
  internal/exporter/prometheus/collector/power_collector_test.go
Labels: fix

#2159 ci: ensure must-gather runs irrespective of failure
  .github/k8s/action.yaml
  .github/workflows/k8s-equinix.yaml
  manifests/k8s/configmap.yaml
Labels: ci

#2160 chore(compose): rename kepler-latest to kepler-old
  compose/dev/compose.yaml
  compose/dev/grafana/dashboards/dev/dashboard.json
  compose/dev/prometheus/scrape-configs/dev.yaml
Labels: chore

#2163 ci: ensure commit-msg precommit runs pr checks
  .github/workflows/pr-checks.yaml
Labels: ci

#2162 feat(pod): retrieve real container name from pod cache
  internal/k8s/pod/pod.go
  internal/k8s/pod/pod_test.go
  internal/resource/informer.go
  internal/resource/mock_procfs_test.go
  internal/resource/procfs_reader_test.go
Labels: chore

#2161 chore: Enable TLS in server creation process
  cmd/kepler/main.go
  config/config_test.go
Labels: chore

#2166 refactor(pod): simplify Lookup returning Container Name
  internal/k8s/pod/pod.go
  internal/k8s/pod/pod_test.go
  internal/resource/informer.go
  internal/resource/mock_procfs_test.go
  internal/resource/procfs_reader_test.go
Labels: refactor

#2175 chore: allow CGO_ENABLED to be set during build
  Makefile
Labels: chore

#2178 chore(Makefile): race checker requires CGO_ENABLED=1
  Makefile
Labels: chore

#2174 feat(metrics): add configurable metrics level filtering for Prometheus exporter
  cmd/kepler/main.go
  compose/dev/kepler-dev/etc/kepler/config.yaml
  config/config.go
  config/config_test.go
  hack/gen-metric-docs/main.go
  internal/exporter/prometheus/collector/power_collector.go
  internal/exporter/prometheus/collector/power_collector_concurrency_test.go
  internal/exporter/prometheus/collector/power_collector_test.go
  internal/exporter/prometheus/metrics/level.go
  internal/exporter/prometheus/metrics/level_test.go
  internal/exporter/prometheus/prometheus.go
Labels: feat

#2176 feat(monitor): add terminated workload tracking and reporting
  docs/metrics/metrics.md
  internal/exporter/prometheus/collector/power_collector.go
  internal/exporter/prometheus/collector/power_collector_test.go
  internal/monitor/container.go
  internal/monitor/container_power_test.go
  internal/monitor/monitor_test.go
  internal/monitor/pod.go
  internal/monitor/pod_power_test.go
  internal/monitor/process.go
  internal/monitor/process_power_test.go
  internal/monitor/types.go
  internal/monitor/vm.go
  internal/monitor/vm_test.go
Labels: test, chore

#2184 chore: fix failing monitor tests
  internal/monitor/container_power_test.go
  internal/monitor/vm_test.go
Labels: chore

#2188 ci: use custom hook for linting PR commits
  .github/workflows/pr-checks.yaml
  .pre-commit-config.yaml
Labels: ci

#2189 ci: enable comment on PR in case of config change
  .github/workflows/config-change.yaml
Labels: ci

#2190 chore: add missing testdata files
  .gitignore
  internal/resource/testdata/fake-root/usr/bin/kepler
  internal/resource/testdata/fake-root/usr/bin/prometheus
  internal/resource/testdata/fake-root/usr/bin/qemu-system-x86
Labels: chore
