Repository sustainable-computing-io/kepler, pull requests merged in 2025-04, with the labels that each got.

#1996 feat(node): node level power from RAPL
  cmd/kepler/main.go
  go.mod
  go.sum
  internal/device/cpu_power_meter.go
  internal/device/cpu_power_meter_test.go
  internal/device/energy.go
  internal/device/energy_test.go
  internal/device/mock_cpu_power_meter.go
  internal/device/rapl_sysfs_power_meter.go
  internal/device/rapl_sysfs_power_meter_test.go
  internal/device/testdata/bad_sysfs/git-keep
  internal/device/testdata/sys/class/powercap/intel-rapl-mmio/enabled
  internal/device/testdata/sys/class/powercap/intel-rapl-mmio/uevent
  internal/device/testdata/sys/class/powercap/intel-rapl-mmio:0/enabled
  internal/device/testdata/sys/class/powercap/intel-rapl-mmio:0/energy_uj
  internal/device/testdata/sys/class/powercap/intel-rapl-mmio:0/max_energy_range_uj
  internal/device/testdata/sys/class/powercap/intel-rapl-mmio:0/name
  internal/device/testdata/sys/class/powercap/intel-rapl/enabled
  internal/device/testdata/sys/class/powercap/intel-rapl/uevent
  internal/device/testdata/sys/class/powercap/intel-rapl:0/enabled
  internal/device/testdata/sys/class/powercap/intel-rapl:0/energy_uj
  internal/device/testdata/sys/class/powercap/intel-rapl:0/max_energy_range_uj
  internal/device/testdata/sys/class/powercap/intel-rapl:0/name
  internal/device/testdata/sys/class/powercap/intel-rapl:0:0/enabled
  internal/device/testdata/sys/class/powercap/intel-rapl:0:0/energy_uj
  internal/device/testdata/sys/class/powercap/intel-rapl:0:0/max_energy_range_uj
  internal/device/testdata/sys/class/powercap/intel-rapl:0:0/name
  internal/device/testdata/sys/class/powercap/intel-rapl:a/enabled
  internal/device/testdata/sys/class/powercap/intel-rapl:a/energy_uj
  internal/device/testdata/sys/class/powercap/intel-rapl:a/max_energy_range_uj
  internal/device/testdata/sys/class/powercap/intel-rapl:a/name
  internal/exporter/prometheus/collectors/power_collector.go
  internal/exporter/prometheus/collectors/power_collector_test.go
  internal/exporter/prometheus/collectors/utils.go
  internal/exporter/prometheus/prometheus.go
  internal/exporter/prometheus/prometheus_test.go
  internal/monitor/mock_cpu_meter_test.go
  internal/monitor/monitor.go
  internal/monitor/monitor_test.go
  internal/monitor/node.go
  internal/monitor/node_test.go
  internal/monitor/options.go
  internal/monitor/types.go
Labels: feat, refactor

#2008 chore(dashboard): enhance Kepler reboot dashboard
  compose/dev/grafana/dashboards/dev/dashboard.json
Labels: chore

#2009 chore: remove custom changelog generation script
  hack/scripts/changelog.sh
  hack/scripts/utils.bash
Labels: chore

#2010 chore(compose): expose config when bringing service up
  compose/dev/compose.yaml
  hack/config.yaml
Labels: chore

#2011 chore(device): add fake CPU power meter for testing
  cmd/kepler/main.go
  config/config.go
  hack/config.yaml
  internal/device/fake_cpu_power_meter.go
  internal/device/fake_cpu_power_meter_test.go
Labels: chore

#2012 test: add negative tests for rapl power meter
  internal/device/rapl_sysfs_power_meter_test.go
Labels: test

#2014 docs: add release workflow sequence diag
  docs/design/assets/release.png
  docs/design/assets/release.uml
  docs/design/release.md
Labels: docs

#2017 chore: rename collectors to collector
  internal/exporter/prometheus/collector/build_info.go
  internal/exporter/prometheus/collector/build_info_test.go
  internal/exporter/prometheus/collector/cpuinfo.go
  internal/exporter/prometheus/collector/cpuinfo_test.go
  internal/exporter/prometheus/collector/power_collector.go
  internal/exporter/prometheus/collector/power_collector_test.go
  internal/exporter/prometheus/collector/utils.go
  internal/exporter/prometheus/prometheus.go
Labels: chore

#2023 fix(cpu_info): change metric name to kepler_node_cpu_info
  internal/exporter/prometheus/collector/cpuinfo.go
  internal/exporter/prometheus/collector/cpuinfo_test.go
Labels: fix

#2021 refactor: service lifecycle into optional Init Run Shutdown
  cmd/kepler/main.go
  internal/device/fake_cpu_power_meter.go
  internal/device/fake_cpu_power_meter_test.go
  internal/device/power_meter.go
  internal/device/rapl_sysfs_power_meter.go
  internal/device/rapl_sysfs_power_meter_test.go
  internal/exporter/prometheus/collector/power_collector_concurrency_test.go
  internal/exporter/prometheus/prometheus.go
  internal/exporter/prometheus/prometheus_test.go
  internal/monitor/mock_cpu_meter_test.go
  internal/monitor/monitor.go
  internal/monitor/monitor_test.go
  internal/server/server.go
  internal/server/server_test.go
  internal/service/service.go
Labels: refactor

#2028 ci: add go vet job
  .github/workflows/pr-checks.yaml
Labels: ci

#2022 refactor(monitor): replace RWMutex with atomic.Pointer for snapshot management
  internal/monitor/monitor.go
  internal/monitor/monitor_concurrency_test.go
  internal/monitor/monitor_test.go
  internal/monitor/node.go
  internal/monitor/node_test.go
Labels: refactor

#2029 feat(pprof): Added pprof
  cmd/kepler/main.go
  config/config.go
  config/config_test.go
  internal/server/pprof.go
  internal/server/pprof_test.go
  internal/server/server.go
Labels: feat

#2026 refactor(service): simplify service lifecycle
  cmd/kepler/main.go
  internal/device/fake_cpu_power_meter.go
  internal/device/fake_cpu_power_meter_test.go
  internal/device/power_meter.go
  internal/device/rapl_sysfs_power_meter.go
  internal/device/rapl_sysfs_power_meter_test.go
  internal/exporter/prometheus/collector/power_collector_concurrency_test.go
  internal/exporter/prometheus/prometheus.go
  internal/exporter/prometheus/prometheus_test.go
  internal/monitor/mock_cpu_meter_test.go
  internal/monitor/monitor.go
  internal/monitor/monitor_concurrency_test.go
  internal/monitor/monitor_test.go
  internal/server/pprof.go
  internal/server/pprof_test.go
  internal/server/server.go
  internal/server/server_test.go
  internal/service/initializer.go
  internal/service/initializer_test.go
  internal/service/mock_service_test.go
  internal/service/run.go
  internal/service/run_test.go
  internal/service/service.go
  internal/service/signal_handler.go
  internal/service/signal_handler_test.go
Labels: refactor

#2034 ci: run jobs based on file changes
  .github/workflows/pr-checks.yaml
Labels: ci

#2031 feat: add RAPL zone filtering support through configuration
  cmd/kepler/main.go
  config/config.go
  config/config_rapl_test.go
  hack/config.yaml
  internal/device/rapl_sysfs_power_meter.go
  internal/device/rapl_zone_filtering_test.go
Labels: feat

#2035 chore(config): add skip validation logic from operator
  config/config.go
  config/config_test.go
Labels: chore

#2016 feat(monitor): improve power monitor with dynamic collection based on interval
  internal/monitor/monitor.go
  internal/monitor/monitor_collection_test.go
  internal/monitor/monitor_concurrency_test.go
  internal/monitor/monitor_test.go
  internal/monitor/options.go
Labels: feat

#2042 docs: add initial readme
  README.md
Labels: docs
