Repository sustainable-computing-io/kepler, pull requests merged in 2025-05, with the labels that each got.

#2058 chore(build): add production build support and enhance debug builds
  Makefile
Labels: chore

#2067 chore: add TLS config to sample config
  hack/config.yaml
Labels: chore

#2065 chore(dashboard): add support for process and container-level metrics
  compose/dev/grafana/dashboards/dev/dashboard.json
Labels: chore

#2072 docs: add monitor and web related config
  docs/configuration/configuration.md
Labels: docs

#2074 chore(logger): prefer buffered stdout over stderr
  cmd/kepler/main.go
  internal/logger/logger.go
  internal/logger/logger_test.go
Labels: chore

#2073 chore: fixes comm and exe not getting updated due to incorrect optimisation
  internal/resource/informer.go
  internal/resource/procfs_reader_test.go
Labels: chore

#2084 fix(container): regex used for detecting kubernete cri containerd
  internal/resource/container.go
  internal/resource/container_test.go
Labels: fix

#2087 ci: capture diff after running make deps
  .github/publish-image/action.yaml
  go.mod
Labels: ci

#2086 ci: enable Kepler deployment on Kind cluster
  Makefile
  README.md
  hack/cluster.sh
  hack/utils.bash
  manifests/k8s/configmap.yaml
  manifests/k8s/daemonset.yaml
  manifests/k8s/kustomization.yaml
  manifests/k8s/namespace.yaml
  manifests/k8s/prometheus-rbac.yaml
  manifests/k8s/rbac.yaml
  manifests/k8s/service.yaml
  manifests/k8s/servicemonitor.yaml
Labels: ci

#2092 chore(k8s): rename config file for kepler
  manifests/k8s/configmap.yaml
  manifests/k8s/daemonset.yaml
Labels: chore

#2088 chore(monitor): refresh process fields on each computation
  internal/monitor/process.go
Labels: chore

#2094 chore: ensure that required precommit hook types are installed
  .pre-commit-config.yaml
Labels: chore

#2095 feat(experiments): added kube-rbac-proxy to kepler openshift deployment
  hack/experiments/kube-rbac-proxy-setup/README.md
  hack/experiments/kube-rbac-proxy-setup/kube-rbac-proxy-secret.yaml
  hack/experiments/kube-rbac-proxy-setup/power-monitor-ca.yaml
  hack/experiments/kube-rbac-proxy-setup/power-monitor-clusterrole.yaml
  hack/experiments/kube-rbac-proxy-setup/power-monitor-clusterrolebinding.yaml
  hack/experiments/kube-rbac-proxy-setup/power-monitor-cm.yaml
  hack/experiments/kube-rbac-proxy-setup/power-monitor-daemonset.yaml
  hack/experiments/kube-rbac-proxy-setup/power-monitor-namespace.yaml
  hack/experiments/kube-rbac-proxy-setup/power-monitor-sa.yaml
  hack/experiments/kube-rbac-proxy-setup/power-monitor-scc.yaml
  hack/experiments/kube-rbac-proxy-setup/power-monitor-service.yaml
  hack/experiments/kube-rbac-proxy-setup/power-monitor-sm.yaml
  hack/experiments/kube-rbac-proxy-setup/test-ca-default.yaml
  hack/experiments/kube-rbac-proxy-setup/test-ca.yaml
  hack/experiments/kube-rbac-proxy-setup/test-correct-job.yaml
  hack/experiments/kube-rbac-proxy-setup/test-sa.yaml
  hack/experiments/kube-rbac-proxy-setup/test-wrong-job.yaml
Labels: feat

#2096 chore(grafana): use uniform color for reboot and old
  compose/dev/grafana/dashboards/dev/dashboard.json
Labels: chore

#2097 chore(grafana): add grafana dashboard download script
  hack/grafana.sh
Labels: chore

#2089 chore(dashboard): test dashboard for node power metrics
  compose/dev/grafana/dashboards/dev/node-dashboard.json
Labels: chore

#2099 ci: add shellcheck and shfmt as precommit hooks
  .pre-commit-config.yaml
Labels: ci

#2104 chore: update k8s configmap with latest config
  Makefile
  manifests/k8s/configmap.yaml
Labels: chore

#2106 ci: add breaking change label
  .github/release.yml
  .github/workflows/assign-labels.yaml
Labels: ci

#2110 fix(resource): ignore deleted process
  internal/resource/informer.go
Labels: fix

#2109 Multiple sockets
  internal/exporter/prometheus/collector/power_collector.go
  internal/exporter/prometheus/collector/power_collector_concurrency_test.go
  internal/exporter/prometheus/collector/power_collector_test.go
Labels: fix

#2100 feat(power): add virtual machine power monitoring
  cmd/kepler/main.go
  internal/exporter/prometheus/collector/power_collector.go
  internal/exporter/prometheus/collector/power_collector_concurrency_test.go
  internal/exporter/prometheus/collector/power_collector_test.go
  internal/monitor/container_power_test.go
  internal/monitor/mock_utils.go
  internal/monitor/monitor.go
  internal/monitor/monitor_collection_test.go
  internal/monitor/monitor_concurrency_test.go
  internal/monitor/monitor_test.go
  internal/monitor/process.go
  internal/monitor/process_power_test.go
  internal/monitor/types.go
  internal/monitor/vm.go
  internal/monitor/vm_test.go
  internal/resource/informer.go
  internal/resource/procfs_reader_test.go
  internal/resource/testdata/README.md
  internal/resource/testdata/copy-pid.sh
  internal/resource/testdata/procfs/1337/exe
  internal/resource/testdata/procfs/3456208/exe
  internal/resource/testdata/procfs/43251/cgroup
  internal/resource/testdata/procfs/43251/cmdline
  internal/resource/testdata/procfs/43251/comm
  internal/resource/testdata/procfs/43251/environ
  internal/resource/testdata/procfs/43251/exe
  internal/resource/testdata/procfs/43251/stat
  internal/resource/types.go
  internal/resource/vm.go
  internal/resource/vm_test.go
Labels: feat

#2114 ci: use git archive for source version checkout
  .github/check-x-crypto/action.yaml
  hack/reports/print-xcrypto-report.sh
Labels: ci

#2112 chore(compose): update dashboard to support recent zone changes
  compose/dev/grafana/dashboards/dev/dashboard.json
Labels: chore

#2111 chore: remove user-monitoring label from service monitor
  hack/experiments/kube-rbac-proxy-setup/power-monitor-sm.yaml
Labels: chore
