Repository sustainable-computing-io/kepler, pull requests merged in 2025-08, with the labels that each got.

#2256 chore: add maintainer cycle
  GOVERNANCE.md
Labels: chore

#2259 chore: add maintainer role to sunya-ch
  MAINTAINERS.md
Labels: chore

#2261 chore: add maintainer role to Sam
  MAINTAINERS.md
Labels: chore

#2264 docs: update docker compose steps
  docs/user/installation.md
Labels: docs

#2269 chore(README): add github star history
  README.md
Labels: chore

#2274 docs: update start command
  docs/user/installation.md
Labels: docs

#2277 fix(vm): add qemu-kvm detection for CentOS/RHEL systems
  internal/resource/vm.go
  internal/resource/vm_test.go
Labels: fix

#2278 docs(proposal): add EP-002 for MSR fallback power meter support
  docs/developer/proposal/EP-002-MSR-Fallback-Power-Meter.md
  docs/developer/proposal/index.md
Labels: docs

#2285 docs: keep the formatting for tables consistent
  .pre-commit-config.yaml
  GOVERNANCE.md
  MAINTAINERS.md
  docs/developer/design/architecture/concurrency.md
  docs/developer/design/architecture/data-flow.md
  docs/developer/design/architecture/index.md
  docs/developer/design/architecture/principles.md
  docs/developer/proposal/index.md
  docs/user/configuration.md
Labels: docs

#2275 ci: add workflow to profile Kepler versions
  .github/workflows/profiling.yaml
  hack/reports/profiling.sh
Labels: ci

#2300 ci: track k8s bm workflow as part of file changes
  .github/workflows/k8s-bm.yaml
Labels: ci
